### ISSUE TITLE
 Typo check at `stakecmd.go`

### ISSUE THREAD

**Issue by sifnoc** [Onther-Tech/plasma-evm#103]
Minor typo`WON` might be `WTON`

https://github.com/Onther-Tech/plasma-evm/blob/6472693c79dfc9694b502cc32aa4dd3ba688989c/cmd/geth/stakecmd.go#L1069

**Comment by 4000D** [comment]
duplicate: #83

**Comment by 4000D** [comment]
fixed: 5bc6ce2a1d285864f0879806eae88acc7ac08d60
