### ISSUE TITLE
cmd/geth : multiple init error

### ISSUE THREAD

**Issue by ggs134** [Onther-Tech/plasma-evm#124]
#### System information

Geth version: 16dfa8acf46edd28307e88e08e251106216bf2a8
OS & Version: ubuntu 18.04
Commit hash : (if `develop`) 16dfa8acf46edd28307e88e08e251106216bf2a8

#### Expected behaviour

multiple init doesn't make any error

#### Actual behaviour

```
ubuntu@ip-172-31-31-234:~/plasma-evm$ build/bin/geth --nousb init genesis.json \
>             --datadir ./operator  \
>             --rootchain.url wss://rinkeby.infura.io/ws/v3/d738213eecc341feb0bf0021390c75e4
INFO [05-11|03:03:34.402] Root chain backend connected             url=wss://rinkeby.infura.io/ws/v3/d738213eecc341feb0bf0021390c75e4
INFO [05-11|03:03:34.599] Stamina config is set                    mindeposit=500000000000000000 recoverepochlength=120960 withdrawaldelay=362880
INFO [05-11|03:03:34.599] Maximum peer count                       ETH=50 LES=0 total=50
INFO [05-11|03:03:34.599] Smartcard socket not found, disabling    err="stat /run/pcscd/pcscd.comm: no such file or directory"
INFO [05-11|03:03:35.604] Set options for submitting a block       mingaspirce=1000000000 maxgasprice=100000000000 resubmit=0s
INFO [05-11|03:03:35.604] Allocated cache and file handles         database=/home/ubuntu/plasma-evm/operator/geth/chaindata cache=16.00MiB handles=16
INFO [05-11|03:03:35.630] Persisted trie from memory database      nodes=19 size=6.26KiB time=88.549µs gcnodes=0 gcsize=0.00B gctime=0s livenodes=1 livesize=-116.00B
Fatal: Failed to write genesis block: database contains incompatible genesis (have 8efa79a5bc52b0eaf4c43d4947ff41289f0166ef7fbff8463b5597a1289c4dec, new 8b3145a803b66727526023dc00e941dfdaba1efbce0362f39be74a377e15fd0a)
```

#### Steps to reproduce the behaviour

1. deploy
2. init
2. deploy again
3. init again --> error : Failed to write genesis block: database contains incompatible genesis

#### Backtrace

````
[backtrace]
````

**Comment by modagi** [comment]
Are the genesis.json used in 2 and 4 different? If so, you have to remove the previous genesis info(data dir) before init again.

--init command doesn't overwrite genesis block with a different block hash.

**Comment by ggs134** [comment]
Ok, I'll try

**Comment by ggs134** [comment]
or it is better automatically wipe out the data in data directory(except for keystore) when making --init command? what do you think? @modagi

**Comment by modagi** [comment]
This was implemented in go-ethereum, not plasma-evm. So, it would be better to remove data directory first, whild keeping the exisiting behavior.
