### ISSUE TITLE
cmd/geth: need to test RootChainGasPrice flags with cmd

### ISSUE THREAD

**Issue by shingonu** [Onther-Tech/plasma-evm#126]
cmd:
- setManagers
- requestWithdrawal
- processWithdrawal

https://github.com/Onther-Tech/plasma-evm/commit/a695c95550b74f2481057955176e739cb445cdc5

**Comment by ggs134** [comment]
- setManager 
--> --rootchain.gasPrice

- requestWithdrawal
--> --rootchain.gasPrice

- processWithdrawal
--> --rootchain.gasPrice

Is it right?

**Comment by shingonu** [comment]
`set-manager`
--> --rootchain.gasprice

`request-withdrawal`
--> --rootchain.gasprice

`process-withdrawal`
--> --rootchain.gasprice
