### ISSUE TITLE
Docker Image build error.

### ISSUE THREAD

**Issue by sifnoc** [Onther-Tech/plasma-evm#28]
There are some directory path error in Dockerfiles

for Example, 
```Dockerfile
FROM alpine:3.7

RUN \
  apk add --update go git make gcc musl-dev linux-headers ca-certificates && \
  git clone --depth 1 https://github.com/Onther-Tech/plasma-evm && \
  (cd go-ethereum && make geth) && \
  cp go-ethereum/build/bin/geth /geth && \
  apk del go git make gcc musl-dev linux-headers && \
  rm -rf /go-ethereum && rm -rf /var/cache/apk/*
```
Cannot progress after `cd go-ethereum` bacause clone directory name is `plasma-evm`

Should change to `plasma-evm` from `go-ethereum`.
Target files 
`plasma-evm/containers/docker/develop-alpine/Dockerfile`
`plasma-evm/containers/docker/develop-ubuntu/Dockerfile`
`plasma-evm/containers/docker/master-alpine/Dockefile`
`plasma-evm/containers/docker/master-ubuntu/Dockefile`

#### System information
OS & Version: Ubuntu:16.04

#### Expected behaviour
Build Image well

#### Actual behaviour
Could not make build docker image from dockerfile

#### Steps to reproduce the behaviour
`> docker build -f Dockerfile`

#### Backtrace

````
[backtrace]
(20/20) Installing musl-dev (1.1.16-r14)
Executing busybox-1.26.2-r9.trigger
OK: 125 MiB in 32 packages
Cloning into 'plasma-evm'...
/bin/sh: cd: line 1: can't cd to go-ethereum
````

**Comment by 4000D** [comment]
`go-ethereum` should change to `plasma-evm`

**Comment by sifnoc** [comment]
There is not include golang1.10.4 above version on golang ppa - ubuntu 16.04.
Have to Manually install golang 1.10.7 above for now.

**Comment by sifnoc** [comment]
I would like to change docker base from ubuntu to stretch.
https://github.com/Onther-Tech/plasma-evm/blob/727336551e7eb84e35fb042f688850ca82943569/containers/docker/develop-ubuntu/Dockerfile#L1

This one is much lighter.
https://github.com/docker-library/golang/blob/304174c7c604cbb7dd445ab58f479efe98f3bbf4/1.11/stretch/Dockerfile

**Comment by sifnoc** [comment]
I am trying to build docker image, base on `golang:1.11-alpine` image on othere branchs.
