### ISSUE TITLE
Add plasma chain script `--rootchain.url` flag

### ISSUE THREAD

**Issue by sifnoc** [Onther-Tech/plasma-evm#30]
Should consider to add `--rootchain.url` flag into `/run.pls.sh` script, Explicitly.

We can know default params through this line, but need to search for know this.
https://github.com/Onther-Tech/plasma-evm/blob/1efc2256e48e3acd29f5d42bb69a96e8dbbf7ab4/cmd/utils/flags.go#L636-L639

#### System information
OS & Version: Ubuntu:16.04

#### Expected behaviour
Running plasma-evm-geth smoothly

#### Actual behaviour
got error then exit
> Fatal: Error starting protocol stack: dial tcp 127.0.0.1:8546: connect: connection refused 

#### Steps to reproduce the behaviour
`sh ./run.pls.sh` without running geth which open 8546 as websocket.

#### Backtrace
If there no opened websocket port to access rootchain connection, will got error.
```
INFO [01-15|06:39:15.509] Loaded most recent local header          number=0 hash=01ff84…020bc6 td=1 age=49y9mo1d
INFO [01-15|06:39:15.509] Loaded most recent local full block      number=0 hash=01ff84…020bc6 td=1 age=49y9mo1d
INFO [01-15|06:39:15.509] Loaded most recent local fast block      number=0 hash=01ff84…020bc6 td=1 age=49y9mo1d
INFO [01-15|06:39:15.509] Regenerated local transaction journal    transactions=0 accounts=0
Fatal: Error starting protocol stack: dial tcp 127.0.0.1:8546: connect: connection refused
```

For the record, if you insert `--rootchain.url "http://127.0.0.1:8545"` then you got meesage like this.
````
[backtrace]
INFO [01-15|06:46:39.049] Started P2P networking                   self=enode://27e2f06987bb521f0cbb6f1cb8c65dcae8eb1d2217091a802f602fc326f8852f64600cf1d33e9e982cc7dae6af55ab6005c22bbf30dd789c094510e9df19cae9@127.0.0.1:30305
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xb55067]

goroutine 131 [running]:
github.com/Onther-Tech/plasma-evm/pls.(*RootChainManager).runSubmitter(0xc0000322d0)
	/home/plasma-evm/build/_workspace/src/github.com/Onther-Tech/plasma-evm/pls/rootchain_manager.go:259 +0x157
created by github.com/Onther-Tech/plasma-evm/pls.(*RootChainManager).run
	/home/plasma-evm/build/_workspace/src/github.com/Onther-Tech/plasma-evm/pls/rootchain_manager.go:139 +0x65
````

**Comment by 4000D** [comment]
[`run.pls.sh`](https://github.com/Onther-Tech/plasma-evm/blob/1efc2256e48e3acd29f5d42bb69a96e8dbbf7ab4/run.pls.sh) is a shell script for plasma-evm client, especially in accordance with [`run.rootchain.sh`](https://github.com/Onther-Tech/go-ethereum/blob/master/run.rootchain.sh) as desciribing [README](https://github.com/Onther-Tech/plasma-evm/blob/1efc2256e48e3acd29f5d42bb69a96e8dbbf7ab4/README.md#ethereum-client). So run.pls.sh has only one parameter for RootChain contract address without rootchain url as a parameter.

We may consider to use `ganache-cli` as a root chain client if it properly supports websocket and it is compatible with plasma-evm client.

**Comment by sifnoc** [comment]
Okay then, There is no need to add ` --rootchain.url` option into [`run.pls.sh`](https://github.com/Onther-Tech/plasma-evm/blob/1efc2256e48e3acd29f5d42bb69a96e8dbbf7ab4/run.pls.sh)
