### ISSUE TITLE
WON? WTON?

### ISSUE THREAD

**Issue by jason-h23** [Onther-Tech/plasma-evm#83]
Hi there,

please note that this is an issue tracker reserved for bug reports and feature requests.

For general questions please use the gitter channel or the Ethereum stack exchange at https://ethereum.stackexchange.com.

#### System information

Geth version: `geth v1.9.3`
OS & Version: Windows/Linux/OSX
Commit hash : feature/stake

#### Expected behaviour

```
INFO [02-14|05:59:09.579|geth/stakecmd.go:857]          WTON Balance                              amount="0 WTON"      depositor=0x5E3230019fEd7aB462e3AC277E7709B9b2716b4F
```
#### Actual behaviour
```
INFO [02-14|05:59:09.579|geth/stakecmd.go:857]          WON Balance                              amount="0 WTON"      depositor=0x5E3230019fEd7aB462e3AC277E7709B9b2716b4F
```

#### Steps to reproduce the behaviour
It occurs when I'm running staking balances command.

**Comment by 4000D** [comment]
fixed: 5bc6ce2a1d285864f0879806eae88acc7ac08d60
