### ISSUE TITLE
Fix cmd/bootnode

### ISSUE THREAD

**Issue by 4000D** [Onther-Tech/plasma-evm#94]
`bootnode` to peer discovery doesn't work currently. should be fixed.

This issues covers 
 - [x] fix `cmd/bootnode` or other packages
 - [x] update puppeth bootnode deployment (not full node)
 - [x] add puppeth deployment type: full node (public node for JSONRPC or others..)

**Comment by sifnoc** [comment]
cmd/bootnode is fine, It was network issue for p2p networking

**Comment by 4000D** [comment]
merged: #98
